### ISSUE TITLE
Sentry init

### ISSUE THREAD

**Issue by NanneHuiges** [docker-library/sentry#11]
From this PR  https://github.com/docker-library/sentry/pull/8 on, there is no config file anymore.
As mentioned in that PR:

> From now on, "sentry init" is going to be required for generating a sane sentry.conf.py.

If you fail to do this, you get this error:

>ValueError: Configuration file does not exist at '/.sentry/sentry.conf.py'

So what to do after doing, essentially, a `docker run progress` and `docker run sentry`?
The sentry container is stopped now, and we need to run sentry init and have that config inside your container. And keep it there.

There is no mention of how to run the init, but I believe the basics would be something like this

```
sudo docker run -it --rm --link some-postgres:postgres sentry sentry init /home/user/.sentry/sentry.conf.py
```

this does create a sentry.conf.py somewhere, but where? Because if I want to go on and create a superuser as the README.md suggest, I still get the issue with the config file:

```
sudo docker run -it --rm --link some-postgres:postgres sentry sentry --config=/home/user/.sentry/sentry.conf.py createsuperuser
```
> ValueError: Configuration file does not exist at '/home/user/.sentry/sentry.conf.py'

**Comment by yosifkit** [comment]
On your first run you'll need to get the file out of the container. Since the `--rm` will delete the container once it stops, you'll need to get it while it is still running. Try using a `-v /local/dir/:home/user/.sentry/` and then the same `-v` with the next run.

**Comment by NanneHuiges** [comment]
ok, that sounds doable I guess, I'lll try that later this week. It might be a good one to add to the Readme later on.

**Comment by guilhermebr** [comment]
I made:
```
$ docker run -ti --name sentry --link some-postgres:postgres --link some0redis:redis -p 3000:9000  sentry bash
# sentry init /home/user/.sentry/sentry.conf.py

$ docker start sentry
```

**Comment by tianon** [comment]
I thought I'd filed an issue specifically about documenting this in https://github.com/docker-library/docs/blob/master/sentry/content.md, but I can't find it now.  This process definitely needs to be documented, since it's not as trivial as the current description leads one to believe.

**Comment by tianon** [comment]
This is fixed now! :+1:
