### ISSUE TITLE
Are celery workers needed, and if so, how to start those?

### ISSUE THREAD

**Issue by NanneHuiges** [docker-library/sentry#12]
How does this install run the celery workers? From the [official sentry quickstart][1] we can read this:

> So do not forget to run the workers!
>
>sentry --config=/etc/sentry.conf.py celery worker -B  
>
>Technically there is a way to run sentry without the queues by setting CELERY_ALWAYS_EAGER to True but this is heavily discouraged and not supported.

I suppose that the discouraged/unsupported eager settings isn't the way forward, but what is?

There is a celery docker in the library, should we run celery in a separate container? Or try to start it inside the running sentry container (that's a docker anti-pattern, isn't it?). 

Anyway, some pointers would be welcome. If I get it running in a "docker compatible" way I'll be glad to do a PR for the README.

I suppose this library is working for some, so it's all too possible I just missed the part where it is really obvious how this works, but there it is ;)

[1]:http://sentry.readthedocs.org/en/latest/quickstart/

**Comment by mountainpaul** [comment]
Did you get this to work?

**Comment by NanneHuiges** [comment]
Nope, not really. I got it to start and then I had to see how the whole celery thing would work. Wasn't worth the hassle at this point, as I went to this library for ease, not for hacking; why re-invent the wheel :)

I did look up a docker-compose thing that sorta did the trick, but i don;t have the link ready. It was nothing too special, just a google-hit on something like docker, compose, sentry. That was better as you get more clearity about what is where

**Comment by mlaitinen** [comment]
I got the celery worker running in another container using the official Sentry image (slightly modified, only added slack integration).

Here's what I got in my sentry.sh:
```
#!/bin/bash
docker run --name sentry --restart=always --link redis:redis --link pg:postgres -d -v /root/sentry/sentry.conf.py:/home/user/.sentry/sentry.conf.py -e SENTRY_DB_PASSWORD=<db password> -e VIRTUAL_HOST=<virtualhost used by nginx-proxy> my_sentry_image
docker run --name sentry_celery --restart=always --link redis:redis --link pg:postgres -d -v /root/sentry/sentry.conf.py:/home/user/.sentry/sentry.conf.py -e SENTRY_DB_PASSWORD=<db password> my_sentry_image sentry celery worker -B -l INFO
```

**Comment by NanneHuiges** [comment]
Is this based on the current (new) repo here, the one from yesterday?

**Comment by mlaitinen** [comment]
Actually, no, but thanks informing me about the latest commit. I didn't notice it until now.

I believe the same commands apply to the latest commit as well.

**Comment by NanneHuiges** [comment]
Yeah, I was trying to see how to get it all in one 'howto', from scratch. so with the create user command, starting the links, etc etc, so i'll add this to the 'todo' list :). Give me a shout if you used the new version and it worked :)

**Comment by yosifkit** [comment]
A new image based on yesterday's changes should be on the Docker Hub later today, or you can clone and docker build if you are in a hurry.  Let me know if it works out and if there needs to be any other additions to the docs (https://github.com/docker-library/docs/pull/289).

**Comment by tianon** [comment]
This is documented in the docs now. :+1:
