### ISSUE TITLE
Setup failing

### ISSUE THREAD

**Issue by ApfelUser** [docker-library/sentry#14]
The docker image is failing setup by this command from the documentation:

```
docker run -it --rm --link some-postgres:postgres sentry sentry createsuperuser
```

and this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/runner.py", line 428, in main
    initializer=initialize_app,
  File "/usr/local/lib/python2.7/site-packages/logan/runner.py", line 191, in run_app
    configure_app(config_path=config_path, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/logan/runner.py", line 104, in configure_app
    raise ValueError("Configuration file does not exist at %r" % (config_path,))
ValueError: Configuration file does not exist at '/home/user/.sentry/sentry.conf.py'
```

**Comment by ApfelUser** [comment]
Any updates?

**Comment by yosifkit** [comment]
We are working on a branch to hopefully fix this and make it easier to run sentry.  It will include a conf file to automatically work with linked postgres/mysql, redis, and memcached containers.  Currently it is in https://github.com/infosiftr/sentry/tree/conf.  I welcome any feedback.

**Comment by NanneHuiges** [comment]
Not sure where you want the feedback, so putting it here :) 

The thing I was lacking apart from the config file, is the celery workers. They should be started (I believe) to get everything up and running, but a quick look in your proposed branch doesn't seem to start them?

I could be way off the mark here, as I'm not an expert, but I needed to fiddle with the workers to get my manual test-install going, so I suppose a docker-version should also have them?

**Comment by tianon** [comment]
The workers should be run separately, especially in separate containers.
:smile:

**Comment by NanneHuiges** [comment]
Yeah, I looked at the links file and didn't see the workers, that's why I feedbacked it :)

**Comment by thelinuxlich** [comment]
+1

**Comment by tianon** [comment]
This is fixed and updated in the documentation now. :+1:

**Comment by lenovouser** [comment]
@tianon I am still getting this error somehow.

**Comment by mattrobenolt** [comment]
@lenovouser Are you using the latest version? 8.1.2?

**Comment by lenovouser** [comment]
@mattrobenolt I thought I was because I used `:latest`, but it used a older version somehow. Got some other issues now though, will create a new issue for that. Thanks!
