### ISSUE TITLE
How to setup the username and password of database at first

### ISSUE THREAD

**Issue by tobegit3hub** [docker-library/sentry#3]
Referring to the tutorial of this container, we should setup MySQL or PostgreSQL first. But I don't know what are the username and password that sentry will use.

We can simply start MySQL container like ` docker run -d --name some-mysql -e MYSQL_ROOT_PASSWORD=root  mysql` but it seems not work.

Please add more information of the complete processes to start sentry :smiley:

**Comment by tobegit3hub** [comment]
And I have this issue.

```
➜ sudo docker run --name some-sentry --link some-mysql:mysql -d sentry
e888fcf2976a9ce90f80b28bb4c822c07f7e0235e3980e2a33ea7ddeb0ff18ce                
➜ sudo docker logs some-sentry
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 9, in <module>
    load_entry_point('sentry==6.4.4', 'console_scripts', 'sentry')()
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/runner.py", line 310, in main
    initializer=initialize_app,
  File "/usr/local/lib/python2.7/site-packages/logan/runner.py", line 167, in run_app
    configure_app(config_path=config_path, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/logan/runner.py", line 89, in configure_app
    raise ValueError("Configuration file does not exist at %r" % (config_path,))
ValueError: Configuration file does not exist at '/.sentry/sentry.conf.py'
```

**Comment by tobegit3hub** [comment]
Thanks @tianon for replying. I hope the readme could give more processes in detail so that everyone could run it step by step :smiley:

**Comment by tianon** [comment]
```console
$ docker run -d --name some-postgres postgres
da03aa22c60d48228a30cb43cb13c1ebe5a61e04eee3833cc5073efdd386c3d2
$ docker run -d --name some-sentry -p 9000:9000 --link some-postgres:postgres sentry
000e21d383d61b1243750acc034a9585e5677ffcf4411ed90b9ae1701987daab
$ docker logs -f some-sentry
... wait for:
2015-01-06 21:01:50 [1] [INFO] Listening at: http://0.0.0.0:9000 (1)
^C
$ curl -sSL 'http://localhost:9000'



<!DOCTYPE html>
<html lang="en">
    <head>
....
```

**Comment by tobegit3hub** [comment]
It works for me with docker 1.4 :smiley: 

The username and password that sentry uses are the default username and password of mysql or postgres containers, right?

**Comment by tobegit3hub** [comment]
I have another question about the default username and password. The document is pool and I can find out them after reading the source files.

**Comment by tobegit3hub** [comment]
I can reset the username and password by following the tutorial. Thanks again.
