### ISSUE TITLE
Cannot start sentry docker -  SENTRY_URL_PREFIX is not configured

### ISSUE THREAD

**Issue by arthurlogilab** [docker-library/sentry#7]
```
# docker logs 8042b...
OperationalError: fe_sendauth: no password supplied

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! SENTRY_URL_PREFIX is not configured !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Performing upgrade before service startup...
Syncing...
```

SENTRY_URL_PREFIX is set in sentry.conf.py

**Comment by arthurlogilab** [comment]
This warning was not the problem, I was missing the --env SENTRY_DB_PASSWORD=mypassword in the docker run command. 

Maybe the readme should reflect the need for this ?

**Comment by yosifkit** [comment]
It looks like sentry just needs an update to grab the postgres user and password from the linked ENV vars.

**Comment by yurireeis** [comment]
> This warning was not the problem, I was missing the --env SENTRY_DB_PASSWORD=mypassword in the docker run command.
> 
> Maybe the readme should reflect the need for this ?

We need to set SENTRY_DB_USER as well on .env vars
